/** @file auto.c
 * @brief File for autonomous code
 *
 * This file should contain the user autonomous() function and any functions related to it.
 *
 * Copyright (c) 2011-2014, Purdue University ACM SIG BOTS.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of Purdue University ACM SIG BOTS nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL PURDUE UNIVERSITY ACM SIG BOTS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Purdue Robotics OS contains FreeRTOS (http://www.freertos.org) whose source code may be
 * obtained from http://sourceforge.net/projects/freertos/files/ or on request.
 */

// Code automatically generated by 750Evo

#include "main.h"

// ------------------ TIMERS --------------------
#define NUM_TIMERS 10
long milliTimers[NUM_TIMERS];
long microTimers[NUM_TIMERS];
bool stopped[NUM_TIMERS];

void startTimer(int num, bool useMilli) {
	if (useMilli) {
		milliTimers[num] = millis();
	} else {
		microTimers[num] = micros();
	}
	if (stopped[num]) {
		stopped[num] = false;
	}
}

long getTimer(int num, bool useMilli) {
	if (stopped[num]) {
		return 0;
	}

	if (useMilli) {
		return millis() - milliTimers[num];
	} else {
		return micros() - microTimers[num];
	}
}

long lapTimer(int num, bool useMilli) {
	if (stopped[num]) {
		return 0;
	}

	long returnVal = getTimer(num, useMilli);
	startTimer(num, useMilli);
	return returnVal;
}

void stopTimer(int num) {
	stopped[num] = true;
}
// ------------------ TIMERS --------------------

int *nextPoint;

float **pattern1;
float **pattern2;

void movePair1(void *data) {
	int ***dataPointer = (int ***)data;
	int **points = *dataPointer;

	int numPatterns = points[0][0];
	int *numRanges = malloc(numPatterns * sizeof(int));
	int **rangeStartVals = malloc(numPatterns * sizeof(int *));
	int **rangeLens = malloc(numPatterns * sizeof(int *));
	int totalLines = 1;
	for (int i = 0; i < numPatterns; i++) {
		numRanges[i] = points[i + 1][0];
		rangeStartVals[i] = (numRanges[i] == 0 ? NULL : malloc(numRanges[i] * sizeof(int)));
		rangeLens[i] = (numRanges[i] == 0 ? NULL : malloc(numRanges[i] * sizeof(int)));
		for (int j = 0; j < numRanges[i]; j++) {
			rangeStartVals[i][j] = points[i + 1 + j + 1][0];
			rangeLens[i][j] = points[i + 1 + j + 1][1];
		}
		totalLines += 1 + numRanges[i];
	}

	int startPoint = totalLines + 1;

	int numPoints = points[startPoint][0];
	nextPoint[0] = startPoint + 1;

	startTimer(1, true);
	int currPoint = nextPoint[0] - (startPoint + 1);
	bool stillChecking = true;

	for (int i = 0; i < numPatterns; i++) {
		for (int j = 0; j < numRanges[i]; j++) {
			if (rangeStartVals[i][j] <= currPoint &&
					rangeStartVals[i][j] + rangeLens[i][j] >= currPoint) {
				motorSet(1, points[nextPoint[0]][0] * pattern1[i][0]);
				motorSet(2, points[nextPoint[0]][0] * pattern1[i][1]);
				motorSet(3, points[nextPoint[0]][0] * pattern1[i][2]);
				motorSet(8, points[nextPoint[0]][0] * pattern1[i][3]);
				motorSet(9, points[nextPoint[0]][0] * pattern1[i][4]);
				motorSet(10, points[nextPoint[0]][0] * pattern1[i][5]);

				stillChecking = false;
				break;
			}
		}

		if (!stillChecking) {
			break;
		}
	}

	if (stillChecking) {
		motorSet(1, points[nextPoint[0]][0]);
		motorSet(2, points[nextPoint[0]][1]);
		motorSet(3, points[nextPoint[0]][2]);
		motorSet(8, points[nextPoint[0]][3]);
		motorSet(9, points[nextPoint[0]][4]);
		motorSet(10, points[nextPoint[0]][5]);
	}

	nextPoint[0]++;

	int *dir = malloc(1 * sizeof(int));
	for (int i = 0; i < 1; i++) {
		dir[i] = (abs(points[nextPoint[0]][6 + i]) - abs(points[nextPoint[0] - 1][6 + i]) >= 0 ? 1 : -1);
	}

	while (nextPoint[0] < numPoints + startPoint) {
		if (dir[0] * abs(getTimer(1, true)) > dir[0] * (abs(points[nextPoint[0]][7] - (points[nextPoint[0]][7] >= 0 ? 1 : -1) * 5))) {
			currPoint = nextPoint[0] - (startPoint + 1);
			stillChecking = true;

			for (int i = 0; i < numPatterns; i++) {
				for (int j = 0; j < numRanges[i]; j++) {
					if (rangeStartVals[i][j] <= currPoint &&
							rangeStartVals[i][j] + rangeLens[i][j] >= currPoint) {
						motorSet(1, points[nextPoint[0]][0] * pattern1[i][0]);
						motorSet(2, points[nextPoint[0]][0] * pattern1[i][1]);
						motorSet(3, points[nextPoint[0]][0] * pattern1[i][2]);
						motorSet(8, points[nextPoint[0]][0] * pattern1[i][3]);
						motorSet(9, points[nextPoint[0]][0] * pattern1[i][4]);
						motorSet(10, points[nextPoint[0]][0] * pattern1[i][5]);

						stillChecking = false;
						break;
					}
				}

				if (!stillChecking) {
					break;
				}
			}

			if (stillChecking) {
				motorSet(1, points[nextPoint[0]][0]);
				motorSet(2, points[nextPoint[0]][1]);
				motorSet(3, points[nextPoint[0]][2]);
				motorSet(8, points[nextPoint[0]][3]);
				motorSet(9, points[nextPoint[0]][4]);
				motorSet(10, points[nextPoint[0]][5]);
			}

			nextPoint[0]++;

			if (nextPoint[0] < numPoints + 1) {
				for (int i = 0; i < 1; i++) {
					dir[i] = (abs(points[nextPoint[0]][6 + i]) - abs(points[nextPoint[0] - 1][6 + i]) > 0 ? 1 : -1);
				}
			}
		}
		delay(20);
	}
	stopTimer(1);
	motorStop(1);
	motorStop(2);
	motorStop(3);
	motorStop(8);
	motorStop(9);
	motorStop(10);
	for(int i = 0; i < numPoints + 1; i++) {
		free(points[i]);
	}
	free(points);
	free(dir);
	for (int i = 0; i < numPatterns; i++) {
		for (int j = 0; j < numRanges[i]; j++) {
			free(rangeStartVals[i][j]);
			free(rangeLens[i][j]);
		}
		free(numRanges[i]);
		free(rangeStartVals[i]);
		free(rangeLens[i]);
	}
	free(numRanges);
	free(rangeStartVals);
	free(rangeLens);
}

void movePair2(void *data) {
	int ***dataPointer = (int ***)data;
	int **points = *dataPointer;
	int numPoints = points[0][0];
	nextPoint[1] = 1;

	motorSet(4, points[nextPoint[1]][0]);
	motorSet(5, points[nextPoint[1]][1]);
	motorSet(6, points[nextPoint[1]][2]);
	motorSet(7, points[nextPoint[1]][3]);
	nextPoint[1]++;

	int *dir = malloc(2 * sizeof(int));
	for (int i = 0; i < 2; i++) {
		dir[i] = (abs(points[nextPoint[1]][4 + i]) - abs(points[nextPoint[1] - 1][4 + i]) >= 0 ? 1 : -1);
	}

	while (nextPoint[1] < numPoints + 1) {
		if (dir[0] * abs(analogRead(1)) > dir[0] * (abs(points[nextPoint[1]][6] - (points[nextPoint[1]][6] >= 0 ? 1 : -1) * 5)) &&
				dir[1] * abs(analogRead(2)) > dir[1] * (abs(points[nextPoint[1]][6] - (points[nextPoint[1]][6] >= 0 ? 1 : -1) * 5))) {
			motorSet(4, points[nextPoint[1]][0]);
			motorSet(5, points[nextPoint[1]][1]);
			motorSet(6, points[nextPoint[1]][2]);
			motorSet(7, points[nextPoint[1]][3]);
			nextPoint[1]++;
			if (nextPoint[1] < numPoints + 1) {
				for (int i = 0; i < 2; i++) {
					dir[i] = (abs(points[nextPoint[1]][4 + i]) - abs(points[nextPoint[1] - 1][4 + i]) > 0 ? 1 : -1);
				}
			}
		}
		delay(20);
	}
	motorStop(4);
	motorStop(5);
	motorStop(6);
	motorStop(7);
	for(int i = 0; i < numPoints + 1; i++) {
		free(points[i]);
	}
	free(points);
	free(dir);
}

bool isRunning(void) {
	for (int i = 1; i <= 10; i++) {
		if (motorGet(i) != 0) {
			return true;
		}
	}
	return false;
}

void waitThenDelay(int ms) {
	while (isRunning()) {
		delay(20);
	}
	delay(ms);
}

/*
 * Runs the user autonomous code. This function will be started in its own task with the default
 * priority and stack size whenever the robot is enabled via the Field Management System or the
 * VEX Competition Switch in the autonomous mode. If the robot is disabled or communications is
 * lost, the autonomous task will be stopped by the kernel. Re-enabling the robot will restart
 * the task, not re-start it from where it left off.
 *
 * Code running in the autonomous task cannot access information from the VEX Joystick. However,
 * the autonomous function can be invoked from another task if a VEX Competition Switch is not
 * available, and it can access joystick information if called in this way.
 *
 * The autonomous task may exit, unlike operatorControl() which should never exit. If it does
 * so, the robot will await a switch to another mode or disable/enable cycle.
 */
void autonomous() {
	nextPoint = malloc(3 * sizeof(int));
	for (int i = 0; i < 3; i++) {
		nextPoint[i] = -1;
	}

	pattern1 = malloc(2 * sizeof(float *));
	for (int i = 0; i < 2; i++) {
		pattern1[i] = malloc(6 * sizeof(float));
	}
	// pattern1[0][0] =

	/*int **points1 = malloc(10 * sizeof(int *));
	for (int i = 0; i < 10; i++) {
		points1[i] = malloc(6 * sizeof(int));
	}
	points1[0][0] = 9;
	points1[1][0] = 13, points1[1][1] = 13, points1[1][2] = -13, points1[1][3] = -13, points1[1][4] = 68, points1[1][5] = 1337;
	points1[2][0] = 12, points1[2][1] = 12, points1[2][2] = -12, points1[2][3] = -12, points1[2][4] = 69, points1[2][5] = 1341;
	points1[3][0] = 12, points1[3][1] = 12, points1[3][2] = -12, points1[3][3] = -12, points1[3][4] = 69, points1[3][5] = 1340;
	points1[4][0] = 10, points1[4][1] = 10, points1[4][2] = -10, points1[4][3] = -10, points1[4][4] = 69, points1[4][5] = 1337;
	points1[5][0] = 10, points1[5][1] = 10, points1[5][2] = -10, points1[5][3] = -10, points1[5][4] = 68, points1[5][5] = 1342;
	points1[6][0] = 8, points1[6][1] = 8, points1[6][2] = -8, points1[6][3] = -8, points1[6][4] = 68, points1[6][5] = 1342;
	points1[7][0] = 8, points1[7][1] = 8, points1[7][2] = -8, points1[7][3] = -8, points1[7][4] = 68, points1[7][5] = 1343;
	points1[8][0] = 7, points1[8][1] = 7, points1[8][2] = -7, points1[8][3] = -7, points1[8][4] = 68, points1[8][5] = 1340;
	points1[9][0] = 0, points1[9][1] = 0, points1[9][2] = 0, points1[9][3] = 0, points1[9][4] = 68, points1[9][5] = 1338;
	void *pass1 = (void *)(&points1);

	bool stillChecking = true;
	TaskHandle run1 = taskCreate(movePair2, TASK_DEFAULT_STACK_SIZE / 2, pass1, TASK_PRIORITY_DEFAULT);
	while (taskGetState(run1) == TASK_RUNNABLE || taskGetState(run1) == TASK_SLEEPING) {
		delay(20);
	}
	waitThenDelay(40);*/

	/*int **points2 = malloc(9 * sizeof(int *));
	for (int i = 0; i < 9; i++) {
		points2[i] = malloc(6 * sizeof(int));
	}
	points2[0][0] = 8;
	points2[1][0] = -7, points2[1][1] = -7, points2[1][2] = 7, points2[1][3] = 7, points2[1][4] = 68, points2[1][5] = 1339;
	points2[2][0] = -13, points2[2][1] = -13, points2[2][2] = 13, points2[2][3] = 13, points2[2][4] = 69, points2[2][5] = 1342;
	points2[3][0] = -14, points2[3][1] = -14, points2[3][2] = 14, points2[3][3] = 14, points2[3][4] = 68, points2[3][5] = 1341;
	points2[4][0] = -14, points2[4][1] = -14, points2[4][2] = 14, points2[4][3] = 14, points2[4][4] = 69, points2[4][5] = 1340;
	points2[5][0] = -15, points2[5][1] = -15, points2[5][2] = 15, points2[5][3] = 15, points2[5][4] = 69, points2[5][5] = 1345;
	points2[6][0] = -15, points2[6][1] = -15, points2[6][2] = 15, points2[6][3] = 15, points2[6][4] = 68, points2[6][5] = 1346;
	points2[7][0] = -7, points2[7][1] = -7, points2[7][2] = 7, points2[7][3] = 7, points2[7][4] = 68, points2[7][5] = 1352;
	points2[8][0] = 0, points2[8][1] = 0, points2[8][2] = 0, points2[8][3] = 0, points2[8][4] = 69, points2[8][5] = 1356;
	void *pass2 = (void *)(&points2);

	stillChecking = true;
	TaskHandle run2 = taskCreate(movePair2, TASK_DEFAULT_STACK_SIZE / 2, pass2, TASK_PRIORITY_DEFAULT);
	while (taskGetState(run2) == TASK_RUNNABLE || taskGetState(run2) == TASK_SLEEPING) {
		delay(20);
	}
	waitThenDelay(180);*/

	int **points3 = malloc(12 * sizeof(int *));
	for (int i = 0; i < 12; i++) {
		points3[i] = malloc(6 * sizeof(int));
	}
	points3[0][0] = 11;
	points3[1][0] = 5, points3[1][1] = 5, points3[1][2] = -5, points3[1][3] = -5, points3[1][4] = 55, points3[1][5] = 1358;
	points3[2][0] = 63, points3[2][1] = 63, points3[2][2] = -63, points3[2][3] = -63, points3[2][4] = 55, points3[2][5] = 1365;
	points3[3][0] = 63, points3[3][1] = 63, points3[3][2] = -63, points3[3][3] = -63, points3[3][4] = 54, points3[3][5] = 1364;
	points3[4][0] = 127, points3[4][1] = 127, points3[4][2] = -127, points3[4][3] = -127, points3[4][4] = 54, points3[4][5] = 1363;
	points3[5][0] = 127, points3[5][1] = 127, points3[5][2] = -127, points3[5][3] = -127, points3[5][4] = 330, points3[5][5] = 1024;
	points3[6][0] = 112, points3[6][1] = 112, points3[6][2] = -112, points3[6][3] = -112, points3[6][4] = 330, points3[6][5] = 1018;
	points3[7][0] = 71, points3[7][1] = 71, points3[7][2] = -71, points3[7][3] = -71, points3[7][4] = 342, points3[7][5] = 1015;
	points3[8][0] = 71, points3[8][1] = 71, points3[8][2] = -71, points3[8][3] = -71, points3[8][4] = 353, points3[8][5] = 1013;
	points3[9][0] = 17, points3[9][1] = 17, points3[9][2] = -17, points3[9][3] = -17, points3[9][4] = 303, points3[9][5] = 1006;
	points3[10][0] = 17, points3[10][1] = 17, points3[10][2] = -17, points3[10][3] = -17, points3[10][4] = 309, points3[10][5] = 996;
	points3[11][0] = 0, points3[11][1] = 0, points3[11][2] = 0, points3[11][3] = 0, points3[11][4] = 299, points3[11][5] = 978;
	void *pass3 = (void *)(&points3);

	bool stillChecking = true;
	TaskHandle run3 = taskCreate(movePair2, TASK_DEFAULT_STACK_SIZE / 2, pass3, TASK_PRIORITY_DEFAULT);
	while (taskGetState(run3) == TASK_RUNNABLE || taskGetState(run3) == TASK_SLEEPING) {
		delay(20);
	}
	waitThenDelay(520);

	int **points4 = malloc(11 * sizeof(int *));
	for (int i = 0; i < 11; i++) {
		points4[i] = malloc(6 * sizeof(int));
	}
	points4[0][0] = 10;
	points4[1][0] = -13, points4[1][1] = -13, points4[1][2] = 13, points4[1][3] = 13, points4[1][4] = 395, points4[1][5] = 965;
	points4[2][0] = -63, points4[2][1] = -63, points4[2][2] = 63, points4[2][3] = 63, points4[2][4] = 394, points4[2][5] = 964;
	points4[3][0] = -63, points4[3][1] = -63, points4[3][2] = 63, points4[3][3] = 63, points4[3][4] = 393, points4[3][5] = 963;
	points4[4][0] = -120, points4[4][1] = -120, points4[4][2] = 120, points4[4][3] = 120, points4[4][4] = 395, points4[4][5] = 967;
	points4[5][0] = -127, points4[5][1] = -127, points4[5][2] = 127, points4[5][3] = 127, points4[5][4] = 396, points4[5][5] = 969;
	points4[6][0] = -127, points4[6][1] = -127, points4[6][2] = 127, points4[6][3] = 127, points4[6][4] = 84, points4[6][5] = 1314;
	points4[7][0] = -113, points4[7][1] = -113, points4[7][2] = 113, points4[7][3] = 113, points4[7][4] = 79, points4[7][5] = 1325;
	points4[8][0] = -113, points4[8][1] = -113, points4[8][2] = 113, points4[8][3] = 113, points4[8][4] = 72, points4[8][5] = 1338;
	points4[9][0] = -13, points4[9][1] = -13, points4[9][2] = 13, points4[9][3] = 13, points4[9][4] = 65, points4[9][5] = 1344;
	points4[10][0] = 0, points4[10][1] = 0, points4[10][2] = 0, points4[10][3] = 0, points4[10][4] = 56, points4[10][5] = 1356;
	void *pass4 = (void *)(&points4);

	int **points5 = malloc(27 * sizeof(int *));
	for (int i = 0; i < 27; i++) {
		points5[i] = malloc(7 * sizeof(int));
	}
	points5[0][0] = 26;
	points5[1][0] = -20, points5[1][1] = 20, points5[1][2] = 20, points5[1][3] = 20, points5[1][4] = 20, points5[1][5] = -20, points5[1][6] = 0;
	points5[2][0] = -29, points5[2][1] = 29, points5[2][2] = 29, points5[2][3] = 29, points5[2][4] = 29, points5[2][5] = -29, points5[2][6] = 21;
	points5[3][0] = -29, points5[3][1] = 29, points5[3][2] = 29, points5[3][3] = 29, points5[3][4] = 29, points5[3][5] = -29, points5[3][6] = 41;
	points5[4][0] = -38, points5[4][1] = 38, points5[4][2] = 38, points5[4][3] = 38, points5[4][4] = 38, points5[4][5] = -38, points5[4][6] = 61;
	points5[5][0] = -38, points5[5][1] = 38, points5[5][2] = 38, points5[5][3] = 38, points5[5][4] = 38, points5[5][5] = -38, points5[5][6] = 81;
	points5[6][0] = -46, points5[6][1] = 46, points5[6][2] = 46, points5[6][3] = 46, points5[6][4] = 46, points5[6][5] = -46, points5[6][6] = 101;
	points5[7][0] = -52, points5[7][1] = 52, points5[7][2] = 52, points5[7][3] = 52, points5[7][4] = 52, points5[7][5] = -52, points5[7][6] = 121;
	points5[8][0] = -52, points5[8][1] = 52, points5[8][2] = 52, points5[8][3] = 52, points5[8][4] = 52, points5[8][5] = -52, points5[8][6] = 141;
	points5[9][0] = -57, points5[9][1] = 57, points5[9][2] = 57, points5[9][3] = 57, points5[9][4] = 57, points5[9][5] = -57, points5[9][6] = 161;
	points5[10][0] = -57, points5[10][1] = 57, points5[10][2] = 57, points5[10][3] = 57, points5[10][4] = 57, points5[10][5] = -57, points5[10][6] = 241;
	points5[11][0] = -60, points5[11][1] = 60, points5[11][2] = 60, points5[11][3] = 60, points5[11][4] = 60, points5[11][5] = -60, points5[11][6] = 261;
	points5[12][0] = -60, points5[12][1] = 60, points5[12][2] = 60, points5[12][3] = 60, points5[12][4] = 60, points5[12][5] = -60, points5[12][6] = 281;
	points5[13][0] = -61, points5[13][1] = 61, points5[13][2] = 61, points5[13][3] = 61, points5[13][4] = 61, points5[13][5] = -61, points5[13][6] = 301;
	points5[14][0] = -61, points5[14][1] = 61, points5[14][2] = 61, points5[14][3] = 61, points5[14][4] = 61, points5[14][5] = -61, points5[14][6] = 381;
	points5[15][0] = -60, points5[15][1] = 60, points5[15][2] = 60, points5[15][3] = 60, points5[15][4] = 60, points5[15][5] = -60, points5[15][6] = 401;
	points5[16][0] = -60, points5[16][1] = 60, points5[16][2] = 60, points5[16][3] = 60, points5[16][4] = 60, points5[16][5] = -60, points5[16][6] = 481;
	points5[17][0] = -57, points5[17][1] = 57, points5[17][2] = 57, points5[17][3] = 57, points5[17][4] = 57, points5[17][5] = -57, points5[17][6] = 501;
	points5[18][0] = -57, points5[18][1] = 57, points5[18][2] = 57, points5[18][3] = 57, points5[18][4] = 57, points5[18][5] = -57, points5[18][6] = 521;
	points5[19][0] = -58, points5[19][1] = 58, points5[19][2] = 58, points5[19][3] = 58, points5[19][4] = 58, points5[19][5] = -58, points5[19][6] = 541;
	points5[20][0] = -58, points5[20][1] = 58, points5[20][2] = 58, points5[20][3] = 58, points5[20][4] = 58, points5[20][5] = -58, points5[20][6] = 621;
	points5[21][0] = -55, points5[21][1] = 55, points5[21][2] = 55, points5[21][3] = 55, points5[21][4] = 55, points5[21][5] = -55, points5[21][6] = 641;
	points5[22][0] = -55, points5[22][1] = 55, points5[22][2] = 55, points5[22][3] = 55, points5[22][4] = 55, points5[22][5] = -55, points5[22][6] = 661;
	points5[23][0] = -51, points5[23][1] = 51, points5[23][2] = 51, points5[23][3] = 51, points5[23][4] = 51, points5[23][5] = -51, points5[23][6] = 681;
	points5[24][0] = -39, points5[24][1] = 39, points5[24][2] = 39, points5[24][3] = 39, points5[24][4] = 39, points5[24][5] = -39, points5[24][6] = 701;
	points5[25][0] = -39, points5[25][1] = 39, points5[25][2] = 39, points5[25][3] = 39, points5[25][4] = 39, points5[25][5] = -39, points5[25][6] = 721;
	points5[26][0] = 0, points5[26][1] = 0, points5[26][2] = 0, points5[26][3] = 0, points5[26][4] = 0, points5[26][5] = 0, points5[26][6] = 741;
	void *pass5 = (void *)(&points5);

	stillChecking = true;
	TaskHandle run4 = taskCreate(movePair2, TASK_DEFAULT_STACK_SIZE / 2, pass4, TASK_PRIORITY_DEFAULT);
	while ((taskGetState(run4) == TASK_RUNNING || taskGetState(run4) == TASK_RUNNABLE ||
			taskGetState(run4) == TASK_SLEEPING) && stillChecking) {
		if (nextPoint[1] >= 1 && abs(analogRead(1)) < abs(254) && abs(analogRead(2)) > abs(1168)) {
			taskCreate(movePair1, TASK_DEFAULT_STACK_SIZE / 2, pass5, TASK_PRIORITY_DEFAULT);
			stillChecking = false;
		}

		delay(5);
	}
	waitThenDelay(161);

	int **points6 = malloc(29 * sizeof(int *));
	for (int i = 0; i < 29; i++) {
		points6[i] = malloc(7 * sizeof(int));
	}
	points6[0][0] = 28;
	points6[1][0] = 21, points6[1][1] = -21, points6[1][2] = 21, points6[1][3] = -21, points6[1][4] = 21, points6[1][5] = -21, points6[1][6] = 20;
	points6[2][0] = 33, points6[2][1] = -33, points6[2][2] = 33, points6[2][3] = -33, points6[2][4] = 33, points6[2][5] = -33, points6[2][6] = 40;
	points6[3][0] = 33, points6[3][1] = -33, points6[3][2] = 33, points6[3][3] = -33, points6[3][4] = 33, points6[3][5] = -33, points6[3][6] = 60;
	points6[4][0] = 40, points6[4][1] = -40, points6[4][2] = 40, points6[4][3] = -40, points6[4][4] = 40, points6[4][5] = -40, points6[4][6] = 80;
	points6[5][0] = 43, points6[5][1] = -43, points6[5][2] = 43, points6[5][3] = -43, points6[5][4] = 43, points6[5][5] = -43, points6[5][6] = 100;
	points6[6][0] = 43, points6[6][1] = -43, points6[6][2] = 43, points6[6][3] = -43, points6[6][4] = 43, points6[6][5] = -43, points6[6][6] = 120;
	points6[7][0] = 45, points6[7][1] = -45, points6[7][2] = 45, points6[7][3] = -45, points6[7][4] = 45, points6[7][5] = -45, points6[7][6] = 140;
	points6[8][0] = 45, points6[8][1] = -45, points6[8][2] = 45, points6[8][3] = -45, points6[8][4] = 45, points6[8][5] = -45, points6[8][6] = 160;
	points6[9][0] = 47, points6[9][1] = -47, points6[9][2] = 47, points6[9][3] = -47, points6[9][4] = 47, points6[9][5] = -47, points6[9][6] = 180;
	points6[10][0] = 47, points6[10][1] = -47, points6[10][2] = 47, points6[10][3] = -47, points6[10][4] = 47, points6[10][5] = -47, points6[10][6] = 380;
	points6[11][0] = 74, points6[11][1] = -74, points6[11][2] = 20, points6[11][3] = -74, points6[11][4] = 20, points6[11][5] = -20, points6[11][6] = 400;
	points6[12][0] = 74, points6[12][1] = -74, points6[12][2] = 20, points6[12][3] = -74, points6[12][4] = 20, points6[12][5] = -20, points6[12][6] = 420;
	points6[13][0] = 81, points6[13][1] = -81, points6[13][2] = 13, points6[13][3] = -81, points6[13][4] = 13, points6[13][5] = -13, points6[13][6] = 440;
	points6[14][0] = 81, points6[14][1] = -81, points6[14][2] = 13, points6[14][3] = -81, points6[14][4] = 13, points6[14][5] = -13, points6[14][6] = 460;
	points6[15][0] = 82, points6[15][1] = -82, points6[15][2] = 12, points6[15][3] = -82, points6[15][4] = 12, points6[15][5] = -12, points6[15][6] = 480;
	points6[16][0] = 67, points6[16][1] = -67, points6[16][2] = 27, points6[16][3] = -67, points6[16][4] = 27, points6[16][5] = -27, points6[16][6] = 500;
	points6[17][0] = 67, points6[17][1] = -67, points6[17][2] = 27, points6[17][3] = -67, points6[17][4] = 27, points6[17][5] = -27, points6[17][6] = 520;
	points6[18][0] = 47, points6[18][1] = -47, points6[18][2] = 47, points6[18][3] = -47, points6[18][4] = 47, points6[18][5] = -47, points6[18][6] = 540;
	points6[19][0] = 47, points6[19][1] = -47, points6[19][2] = 47, points6[19][3] = -47, points6[19][4] = 47, points6[19][5] = -47, points6[19][6] = 680;
	points6[20][0] = 45, points6[20][1] = -45, points6[20][2] = 45, points6[20][3] = -45, points6[20][4] = 45, points6[20][5] = -45, points6[20][6] = 700;
	points6[21][0] = 45, points6[21][1] = -45, points6[21][2] = 45, points6[21][3] = -45, points6[21][4] = 45, points6[21][5] = -45, points6[21][6] = 1361;
	points6[22][0] = 44, points6[22][1] = -44, points6[22][2] = 44, points6[22][3] = -44, points6[22][4] = 44, points6[22][5] = -44, points6[22][6] = 1381;
	points6[23][0] = 44, points6[23][1] = -44, points6[23][2] = 44, points6[23][3] = -44, points6[23][4] = 44, points6[23][5] = -44, points6[23][6] = 1441;
	points6[24][0] = 45, points6[24][1] = -45, points6[24][2] = 45, points6[24][3] = -45, points6[24][4] = 45, points6[24][5] = -45, points6[24][6] = 1461;
	points6[25][0] = 45, points6[25][1] = -45, points6[25][2] = 45, points6[25][3] = -45, points6[25][4] = 45, points6[25][5] = -45, points6[25][6] = 1501;
	points6[26][0] = 39, points6[26][1] = -39, points6[26][2] = 39, points6[26][3] = -39, points6[26][4] = 39, points6[26][5] = -39, points6[26][6] = 1521;
	points6[27][0] = 39, points6[27][1] = -39, points6[27][2] = 39, points6[27][3] = -39, points6[27][4] = 39, points6[27][5] = -39, points6[27][6] = 1541;
	points6[28][0] = 0, points6[28][1] = 0, points6[28][2] = 0, points6[28][3] = 0, points6[28][4] = 0, points6[28][5] = 0, points6[28][6] = 1561;
	void *pass6 = (void *)(&points6);

	int **points7 = malloc(18 * sizeof(int *));
	for (int i = 0; i < 18; i++) {
		points7[i] = malloc(6 * sizeof(int));
	}
	points7[0][0] = 17;
	points7[1][0] = 15, points7[1][1] = 15, points7[1][2] = -15, points7[1][3] = -15, points7[1][4] = 8, points7[1][5] = 1447;
	points7[2][0] = 43, points7[2][1] = 43, points7[2][2] = -43, points7[2][3] = -43, points7[2][4] = 8, points7[2][5] = 1449;
	points7[3][0] = 43, points7[3][1] = 43, points7[3][2] = -43, points7[3][3] = -43, points7[3][4] = 8, points7[3][5] = 1448;
	points7[4][0] = 114, points7[4][1] = 114, points7[4][2] = -114, points7[4][3] = -114, points7[4][4] = 8, points7[4][5] = 1447;
	points7[5][0] = 114, points7[5][1] = 114, points7[5][2] = -114, points7[5][3] = -114, points7[5][4] = 8, points7[5][5] = 1448;
	points7[6][0] = 120, points7[6][1] = 120, points7[6][2] = -120, points7[6][3] = -120, points7[6][4] = 7, points7[6][5] = 1444;
	points7[7][0] = 120, points7[7][1] = 120, points7[7][2] = -120, points7[7][3] = -120, points7[7][4] = 9, points7[7][5] = 1435;
	points7[8][0] = 122, points7[8][1] = 122, points7[8][2] = -122, points7[8][3] = -122, points7[8][4] = 9, points7[8][5] = 1430;
	points7[9][0] = 122, points7[9][1] = 122, points7[9][2] = -122, points7[9][3] = -122, points7[9][4] = 8, points7[9][5] = 1421;
	points7[10][0] = 124, points7[10][1] = 124, points7[10][2] = -124, points7[10][3] = -124, points7[10][4] = 7, points7[10][5] = 1413;
	points7[11][0] = 124, points7[11][1] = 124, points7[11][2] = -124, points7[11][3] = -124, points7[11][4] = 108, points7[11][5] = 1241;
	points7[12][0] = 127, points7[12][1] = 127, points7[12][2] = -127, points7[12][3] = -127, points7[12][4] = 110, points7[12][5] = 1239;
	points7[13][0] = 127, points7[13][1] = 127, points7[13][2] = -127, points7[13][3] = -127, points7[13][4] = 1335, points7[13][5] = 9;
	points7[14][0] = 98, points7[14][1] = 98, points7[14][2] = -98, points7[14][3] = -98, points7[14][4] = 1339, points7[14][5] = 9;
	points7[15][0] = 7, points7[15][1] = 7, points7[15][2] = -7, points7[15][3] = -7, points7[15][4] = 1338, points7[15][5] = 10;
	points7[16][0] = 7, points7[16][1] = 7, points7[16][2] = -7, points7[16][3] = -7, points7[16][4] = 1341, points7[16][5] = 11;
	points7[17][0] = 0, points7[17][1] = 0, points7[17][2] = 0, points7[17][3] = 0, points7[17][4] = 1345, points7[17][5] = 9;
	void *pass7 = (void *)(&points7);

	int **points8 = malloc(21 * sizeof(int *));
	for (int i = 0; i < 21; i++) {
		points8[i] = malloc(7 * sizeof(int));
	}
	points8[0][0] = 20;
	points8[1][0] = -20, points8[1][1] = 20, points8[1][2] = 20, points8[1][3] = 20, points8[1][4] = 20, points8[1][5] = -20, points8[1][6] = 0;
	points8[2][0] = -24, points8[2][1] = 24, points8[2][2] = 24, points8[2][3] = 24, points8[2][4] = 24, points8[2][5] = -24, points8[2][6] = 21;
	points8[3][0] = -24, points8[3][1] = 24, points8[3][2] = 24, points8[3][3] = 24, points8[3][4] = 24, points8[3][5] = -24, points8[3][6] = 41;
	points8[4][0] = -34, points8[4][1] = 34, points8[4][2] = 34, points8[4][3] = 34, points8[4][4] = 34, points8[4][5] = -34, points8[4][6] = 61;
	points8[5][0] = -34, points8[5][1] = 34, points8[5][2] = 34, points8[5][3] = 34, points8[5][4] = 34, points8[5][5] = -34, points8[5][6] = 81;
	points8[6][0] = -39, points8[6][1] = 39, points8[6][2] = 39, points8[6][3] = 39, points8[6][4] = 39, points8[6][5] = -39, points8[6][6] = 101;
	points8[7][0] = -41, points8[7][1] = 41, points8[7][2] = 41, points8[7][3] = 41, points8[7][4] = 41, points8[7][5] = -41, points8[7][6] = 121;
	points8[8][0] = -41, points8[8][1] = 41, points8[8][2] = 41, points8[8][3] = 41, points8[8][4] = 41, points8[8][5] = -41, points8[8][6] = 181;
	points8[9][0] = -38, points8[9][1] = 38, points8[9][2] = 38, points8[9][3] = 38, points8[9][4] = 38, points8[9][5] = -38, points8[9][6] = 201;
	points8[10][0] = -38, points8[10][1] = 38, points8[10][2] = 38, points8[10][3] = 38, points8[10][4] = 38, points8[10][5] = -38, points8[10][6] = 221;
	points8[11][0] = -31, points8[11][1] = 31, points8[11][2] = 31, points8[11][3] = 31, points8[11][4] = 31, points8[11][5] = -31, points8[11][6] = 241;
	points8[12][0] = -26, points8[12][1] = 26, points8[12][2] = 26, points8[12][3] = 26, points8[12][4] = 26, points8[12][5] = -26, points8[12][6] = 261;
	points8[13][0] = -26, points8[13][1] = 26, points8[13][2] = 26, points8[13][3] = 26, points8[13][4] = 26, points8[13][5] = -26, points8[13][6] = 281;
	points8[14][0] = 2, points8[14][1] = -2, points8[14][2] = 46, points8[14][3] = -2, points8[14][4] = 46, points8[14][5] = -46, points8[14][6] = 301;
	points8[15][0] = 2, points8[15][1] = -2, points8[15][2] = 46, points8[15][3] = -2, points8[15][4] = 46, points8[15][5] = -46, points8[15][6] = 321;
	points8[16][0] = 27, points8[16][1] = -27, points8[16][2] = 27, points8[16][3] = -27, points8[16][4] = 27, points8[16][5] = -27, points8[16][6] = 341;
	points8[17][0] = 27, points8[17][1] = -27, points8[17][2] = 27, points8[17][3] = -27, points8[17][4] = 27, points8[17][5] = -27, points8[17][6] = 421;
	points8[18][0] = 24, points8[18][1] = -24, points8[18][2] = 24, points8[18][3] = -24, points8[18][4] = 24, points8[18][5] = -24, points8[18][6] = 441;
	points8[19][0] = 24, points8[19][1] = -24, points8[19][2] = 24, points8[19][3] = -24, points8[19][4] = 24, points8[19][5] = -24, points8[19][6] = 461;
	points8[20][0] = 0, points8[20][1] = 0, points8[20][2] = 0, points8[20][3] = 0, points8[20][4] = 0, points8[20][5] = 0, points8[20][6] = 481;
	void *pass8 = (void *)(&points8);

	stillChecking = true;
	TaskHandle run6 = taskCreate(movePair1, TASK_DEFAULT_STACK_SIZE / 2, pass6, TASK_PRIORITY_DEFAULT);
	while ((taskGetState(run6) == TASK_RUNNING || taskGetState(run6) == TASK_RUNNABLE ||
			taskGetState(run6) == TASK_SLEEPING) && stillChecking) {
		if (nextPoint[0] >= 1 && abs(getTimer(1, true)) > abs(960)) {
			TaskHandle run7 = taskCreate(movePair2, TASK_DEFAULT_STACK_SIZE / 2, pass7, TASK_PRIORITY_DEFAULT);
			while ((taskGetState(run7) == TASK_RUNNING || taskGetState(run7) == TASK_RUNNABLE ||
					taskGetState(run7) == TASK_SLEEPING) && stillChecking) {
				if (nextPoint[1] >= 22 && abs(analogRead(1)) > abs(453) && abs(analogRead(2)) < abs(880)) {
					taskCreate(movePair1, TASK_DEFAULT_STACK_SIZE / 2, pass8, TASK_PRIORITY_DEFAULT);
					stillChecking = false;
				}
				delay(5);
			}
		}

		delay(5);
	}
	waitThenDelay(80);

	int **points9 = malloc(15 * sizeof(int *));
	for (int i = 0; i < 15; i++) {
		points9[i] = malloc(7 * sizeof(int));
	}
	points9[0][0] = 14;
	points9[1][0] = -23, points9[1][1] = 23, points9[1][2] = 23, points9[1][3] = 23, points9[1][4] = 23, points9[1][5] = -23, points9[1][6] = 21;
	points9[2][0] = -38, points9[2][1] = 38, points9[2][2] = 38, points9[2][3] = 38, points9[2][4] = 38, points9[2][5] = -38, points9[2][6] = 41;
	points9[3][0] = -48, points9[3][1] = 48, points9[3][2] = 48, points9[3][3] = 48, points9[3][4] = 48, points9[3][5] = -48, points9[3][6] = 61;
	points9[4][0] = -48, points9[4][1] = 48, points9[4][2] = 48, points9[4][3] = 48, points9[4][4] = 48, points9[4][5] = -48, points9[4][6] = 81;
	points9[5][0] = -52, points9[5][1] = 52, points9[5][2] = 52, points9[5][3] = 52, points9[5][4] = 52, points9[5][5] = -52, points9[5][6] = 101;
	points9[6][0] = -52, points9[6][1] = 52, points9[6][2] = 52, points9[6][3] = 52, points9[6][4] = 52, points9[6][5] = -52, points9[6][6] = 141;
	points9[7][0] = -51, points9[7][1] = 51, points9[7][2] = 51, points9[7][3] = 51, points9[7][4] = 51, points9[7][5] = -51, points9[7][6] = 161;
	points9[8][0] = -51, points9[8][1] = 51, points9[8][2] = 51, points9[8][3] = 51, points9[8][4] = 51, points9[8][5] = -51, points9[8][6] = 181;
	points9[9][0] = -50, points9[9][1] = 50, points9[9][2] = 50, points9[9][3] = 50, points9[9][4] = 50, points9[9][5] = -50, points9[9][6] = 201;
	points9[10][0] = -50, points9[10][1] = 50, points9[10][2] = 50, points9[10][3] = 50, points9[10][4] = 50, points9[10][5] = -50, points9[10][6] = 221;
	points9[11][0] = -42, points9[11][1] = 42, points9[11][2] = 42, points9[11][3] = 42, points9[11][4] = 42, points9[11][5] = -42, points9[11][6] = 241;
	points9[12][0] = -42, points9[12][1] = 42, points9[12][2] = 42, points9[12][3] = 42, points9[12][4] = 42, points9[12][5] = -42, points9[12][6] = 261;
	points9[13][0] = -20, points9[13][1] = 20, points9[13][2] = 20, points9[13][3] = 20, points9[13][4] = 20, points9[13][5] = -20, points9[13][6] = 281;
	points9[14][0] = 0, points9[14][1] = 0, points9[14][2] = 0, points9[14][3] = 0, points9[14][4] = 0, points9[14][5] = 0, points9[14][6] = 301;
	void *pass9 = (void *)(&points9);

	TaskHandle run9 = taskCreate(movePair1, TASK_DEFAULT_STACK_SIZE / 2, pass9, TASK_PRIORITY_DEFAULT);
	while (taskGetState(run9) == TASK_RUNNABLE || taskGetState(run9) == TASK_SLEEPING) {
		delay(20);
	}
	delay(400);

	int **points10 = malloc(14 * sizeof(int *));
	for (int i = 0; i < 14; i++) {
		points10[i] = malloc(7 * sizeof(int));
	}
	points10[0][0] = 13;
	points10[1][0] = 20, points10[1][1] = -20, points10[1][2] = 20, points10[1][3] = -20, points10[1][4] = 20, points10[1][5] = -20, points10[1][6] = 21;
	points10[2][0] = 32, points10[2][1] = -32, points10[2][2] = 32, points10[2][3] = -32, points10[2][4] = 32, points10[2][5] = -32, points10[2][6] = 41;
	points10[3][0] = 32, points10[3][1] = -32, points10[3][2] = 32, points10[3][3] = -32, points10[3][4] = 32, points10[3][5] = -32, points10[3][6] = 61;
	points10[4][0] = 44, points10[4][1] = -44, points10[4][2] = 44, points10[4][3] = -44, points10[4][4] = 44, points10[4][5] = -44, points10[4][6] = 81;
	points10[5][0] = 46, points10[5][1] = -46, points10[5][2] = 46, points10[5][3] = -46, points10[5][4] = 46, points10[5][5] = -46, points10[5][6] = 101;
	points10[6][0] = 46, points10[6][1] = -46, points10[6][2] = 46, points10[6][3] = -46, points10[6][4] = 46, points10[6][5] = -46, points10[6][6] = 161;
	points10[7][0] = 43, points10[7][1] = -43, points10[7][2] = 43, points10[7][3] = -43, points10[7][4] = 43, points10[7][5] = -43, points10[7][6] = 181;
	points10[8][0] = 40, points10[8][1] = -40, points10[8][2] = 40, points10[8][3] = -40, points10[8][4] = 40, points10[8][5] = -40, points10[8][6] = 201;
	points10[9][0] = 40, points10[9][1] = -40, points10[9][2] = 40, points10[9][3] = -40, points10[9][4] = 40, points10[9][5] = -40, points10[9][6] = 381;
	points10[10][0] = 38, points10[10][1] = -38, points10[10][2] = 38, points10[10][3] = -38, points10[10][4] = 38, points10[10][5] = -38, points10[10][6] = 401;
	points10[11][0] = 38, points10[11][1] = -38, points10[11][2] = 38, points10[11][3] = -38, points10[11][4] = 38, points10[11][5] = -38, points10[11][6] = 461;
	points10[12][0] = 29, points10[12][1] = -29, points10[12][2] = 29, points10[12][3] = -29, points10[12][4] = 29, points10[12][5] = -29, points10[12][6] = 481;
	points10[13][0] = 0, points10[13][1] = 0, points10[13][2] = 0, points10[13][3] = 0, points10[13][4] = 0, points10[13][5] = 0, points10[13][6] = 501;
	void *pass10 = (void *)(&points10);

	TaskHandle run10 = taskCreate(movePair1, TASK_DEFAULT_STACK_SIZE / 2, pass10, TASK_PRIORITY_DEFAULT);
	while (taskGetState(run10) == TASK_RUNNABLE || taskGetState(run10) == TASK_SLEEPING) {
		delay(20);
	}
	delay(400);

	int **points11 = malloc(24 * sizeof(int *));
	for (int i = 0; i < 24; i++) {
		points11[i] = malloc(7 * sizeof(int));
	}
	points11[0][0] = 23;
	points11[1][0] = 24, points11[1][1] = -24, points11[1][2] = -24, points11[1][3] = -24, points11[1][4] = -24, points11[1][5] = 24, points11[1][6] = 100;
	points11[2][0] = 21, points11[2][1] = -21, points11[2][2] = -21, points11[2][3] = -21, points11[2][4] = -21, points11[2][5] = 21, points11[2][6] = 120;
	points11[3][0] = 21, points11[3][1] = -21, points11[3][2] = -21, points11[3][3] = -21, points11[3][4] = -21, points11[3][5] = 21, points11[3][6] = 140;
	points11[4][0] = 43, points11[4][1] = -43, points11[4][2] = 43, points11[4][3] = -43, points11[4][4] = 43, points11[4][5] = -43, points11[4][6] = 160;
	points11[5][0] = 43, points11[5][1] = -43, points11[5][2] = 43, points11[5][3] = -43, points11[5][4] = 43, points11[5][5] = -43, points11[5][6] = 180;
	points11[6][0] = 62, points11[6][1] = -62, points11[6][2] = 62, points11[6][3] = -62, points11[6][4] = 62, points11[6][5] = -62, points11[6][6] = 200;
	points11[7][0] = 66, points11[7][1] = -66, points11[7][2] = 66, points11[7][3] = -66, points11[7][4] = 66, points11[7][5] = -66, points11[7][6] = 220;
	points11[8][0] = 66, points11[8][1] = -66, points11[8][2] = 66, points11[8][3] = -66, points11[8][4] = 66, points11[8][5] = -66, points11[8][6] = 240;
	points11[9][0] = 67, points11[9][1] = -67, points11[9][2] = 67, points11[9][3] = -67, points11[9][4] = 67, points11[9][5] = -67, points11[9][6] = 260;
	points11[10][0] = 67, points11[10][1] = -67, points11[10][2] = 67, points11[10][3] = -67, points11[10][4] = 67, points11[10][5] = -67, points11[10][6] = 280;
	points11[11][0] = 71, points11[11][1] = -71, points11[11][2] = 71, points11[11][3] = -71, points11[11][4] = 71, points11[11][5] = -71, points11[11][6] = 300;
	points11[12][0] = 72, points11[12][1] = -72, points11[12][2] = 72, points11[12][3] = -72, points11[12][4] = 72, points11[12][5] = -72, points11[12][6] = 320;
	points11[13][0] = 72, points11[13][1] = -72, points11[13][2] = 72, points11[13][3] = -72, points11[13][4] = 72, points11[13][5] = -72, points11[13][6] = 380;
	points11[14][0] = 73, points11[14][1] = -73, points11[14][2] = 73, points11[14][3] = -73, points11[14][4] = 73, points11[14][5] = -73, points11[14][6] = 400;
	points11[15][0] = 73, points11[15][1] = -73, points11[15][2] = 73, points11[15][3] = -73, points11[15][4] = 73, points11[15][5] = -73, points11[15][6] = 500;
	points11[16][0] = 71, points11[16][1] = -71, points11[16][2] = 71, points11[16][3] = -71, points11[16][4] = 71, points11[16][5] = -71, points11[16][6] = 520;
	points11[17][0] = 71, points11[17][1] = -71, points11[17][2] = 71, points11[17][3] = -71, points11[17][4] = 71, points11[17][5] = -71, points11[17][6] = 540;
	points11[18][0] = 65, points11[18][1] = -65, points11[18][2] = 65, points11[18][3] = -65, points11[18][4] = 65, points11[18][5] = -65, points11[18][6] = 560;
	points11[19][0] = 65, points11[19][1] = -65, points11[19][2] = 65, points11[19][3] = -65, points11[19][4] = 65, points11[19][5] = -65, points11[19][6] = 580;
	points11[20][0] = 48, points11[20][1] = -48, points11[20][2] = 48, points11[20][3] = -48, points11[20][4] = 48, points11[20][5] = -48, points11[20][6] = 600;
	points11[21][0] = 20, points11[21][1] = -20, points11[21][2] = 20, points11[21][3] = -20, points11[21][4] = 20, points11[21][5] = -20, points11[21][6] = 620;
	points11[22][0] = 20, points11[22][1] = -20, points11[22][2] = 20, points11[22][3] = -20, points11[22][4] = 20, points11[22][5] = -20, points11[22][6] = 640;
	points11[23][0] = 0, points11[23][1] = 0, points11[23][2] = 0, points11[23][3] = 0, points11[23][4] = 0, points11[23][5] = 0, points11[23][6] = 660;
	void *pass11 = (void *)(&points11);

	stillChecking = true;
	TaskHandle run11 = taskCreate(movePair1, TASK_DEFAULT_STACK_SIZE / 2, pass11, TASK_PRIORITY_DEFAULT);
	while (taskGetState(run11) == TASK_RUNNABLE || taskGetState(run11) == TASK_SLEEPING) {
		delay(20);
	}
	waitThenDelay(40);

	int **points12 = malloc(6 * sizeof(int *));
	for (int i = 0; i < 6; i++) {
		points12[i] = malloc(7 * sizeof(int));
	}
	points12[0][0] = 5;
	points12[1][0] = 0, points12[1][1] = 50, points12[1][2] = 50, points12[1][3] = -50, points12[1][4] = -50, points12[1][5] = 0, points12[1][6] = 0;
	points12[2][0] = 0, points12[2][1] = 68, points12[2][2] = 68, points12[2][3] = -68, points12[2][4] = -68, points12[2][5] = 0, points12[2][6] = 40;
	points12[3][0] = 0, points12[3][1] = 74, points12[3][2] = 74, points12[3][3] = -74, points12[3][4] = -74, points12[3][5] = 0, points12[3][6] = 100;
	points12[4][0] = 0, points12[4][1] = 71, points12[4][2] = 71, points12[4][3] = -71, points12[4][4] = -71, points12[4][5] = 0, points12[4][6] = 140;
	points12[5][0] = 0, points12[5][1] = 0, points12[5][2] = 0, points12[5][3] = 0, points12[5][4] = 0, points12[5][5] = 0, points12[5][6] = 160;
	void *pass12 = (void *)(&points12);

	stillChecking = true;
	TaskHandle run12 = taskCreate(movePair1, TASK_DEFAULT_STACK_SIZE / 2, pass12, TASK_PRIORITY_DEFAULT);
	while (taskGetState(run12) == TASK_RUNNABLE || taskGetState(run12) == TASK_SLEEPING) {
		delay(20);
	}
	waitThenDelay(60);

	int **points13 = malloc(11 * sizeof(int *));
	for (int i = 0; i < 11; i++) {
		points13[i] = malloc(7 * sizeof(int));
	}
	points13[0][0] = 10;
	points13[1][0] = -34, points13[1][1] = 34, points13[1][2] = 34, points13[1][3] = 34, points13[1][4] = 34, points13[1][5] = -34, points13[1][6] = 20;
	points13[2][0] = -56, points13[2][1] = 56, points13[2][2] = 56, points13[2][3] = 56, points13[2][4] = 56, points13[2][5] = -56, points13[2][6] = 40;
	points13[3][0] = -56, points13[3][1] = 56, points13[3][2] = 56, points13[3][3] = 56, points13[3][4] = 56, points13[3][5] = -56, points13[3][6] = 60;
	points13[4][0] = -69, points13[4][1] = 69, points13[4][2] = 69, points13[4][3] = 69, points13[4][4] = 69, points13[4][5] = -69, points13[4][6] = 80;
	points13[5][0] = -75, points13[5][1] = 75, points13[5][2] = 75, points13[5][3] = 75, points13[5][4] = 75, points13[5][5] = -75, points13[5][6] = 100;
	points13[6][0] = -75, points13[6][1] = 75, points13[6][2] = 75, points13[6][3] = 75, points13[6][4] = 75, points13[6][5] = -75, points13[6][6] = 120;
	points13[7][0] = -74, points13[7][1] = 74, points13[7][2] = 74, points13[7][3] = 74, points13[7][4] = 74, points13[7][5] = -74, points13[7][6] = 140;
	points13[8][0] = -74, points13[8][1] = 74, points13[8][2] = 74, points13[8][3] = 74, points13[8][4] = 74, points13[8][5] = -74, points13[8][6] = 160;
	points13[9][0] = -51, points13[9][1] = 51, points13[9][2] = 51, points13[9][3] = 51, points13[9][4] = 51, points13[9][5] = -51, points13[9][6] = 180;
	points13[10][0] = 0, points13[10][1] = 0, points13[10][2] = 0, points13[10][3] = 0, points13[10][4] = 0, points13[10][5] = 0, points13[10][6] = 200;
	void *pass13 = (void *)(&points13);

	stillChecking = true;
	TaskHandle run13 = taskCreate(movePair1, TASK_DEFAULT_STACK_SIZE / 2, pass13, TASK_PRIORITY_DEFAULT);
	while (taskGetState(run13) == TASK_RUNNABLE || taskGetState(run13) == TASK_SLEEPING) {
		delay(20);
	}
	waitThenDelay(280);

	int **points14 = malloc(24 * sizeof(int *));
	for (int i = 0; i < 24; i++) {
		points14[i] = malloc(7 * sizeof(int));
	}
	points14[0][0] = 23;
	points14[1][0] = 0, points14[1][1] = 32, points14[1][2] = 32, points14[1][3] = -32, points14[1][4] = -32, points14[1][5] = 0, points14[1][6] = 0;
	points14[2][0] = 0, points14[2][1] = 35, points14[2][2] = 35, points14[2][3] = -35, points14[2][4] = -35, points14[2][5] = 0, points14[2][6] = 40;
	points14[3][0] = 0, points14[3][1] = 36, points14[3][2] = 36, points14[3][3] = -36, points14[3][4] = -36, points14[3][5] = 0, points14[3][6] = 80;
	points14[4][0] = 0, points14[4][1] = 42, points14[4][2] = 42, points14[4][3] = -42, points14[4][4] = -42, points14[4][5] = 0, points14[4][6] = 100;
	points14[5][0] = 0, points14[5][1] = 54, points14[5][2] = 54, points14[5][3] = -54, points14[5][4] = -54, points14[5][5] = 0, points14[5][6] = 140;
	points14[6][0] = 0, points14[6][1] = 58, points14[6][2] = 58, points14[6][3] = -58, points14[6][4] = -58, points14[6][5] = 0, points14[6][6] = 200;
	points14[7][0] = 0, points14[7][1] = 56, points14[7][2] = 56, points14[7][3] = -56, points14[7][4] = -56, points14[7][5] = 0, points14[7][6] = 240;
	points14[8][0] = 0, points14[8][1] = 52, points14[8][2] = 52, points14[8][3] = -52, points14[8][4] = -52, points14[8][5] = 0, points14[8][6] = 280;
	points14[9][0] = 0, points14[9][1] = 47, points14[9][2] = 47, points14[9][3] = -47, points14[9][4] = -47, points14[9][5] = 0, points14[9][6] = 300;
	points14[10][0] = 0, points14[10][1] = 42, points14[10][2] = 42, points14[10][3] = -42, points14[10][4] = -42, points14[10][5] = 0, points14[10][6] = 340;
	points14[11][0] = 0, points14[11][1] = 39, points14[11][2] = 39, points14[11][3] = -39, points14[11][4] = -39, points14[11][5] = 0, points14[11][6] = 380;
	points14[12][0] = 0, points14[12][1] = 44, points14[12][2] = 44, points14[12][3] = -44, points14[12][4] = -44, points14[12][5] = 0, points14[12][6] = 400;
	points14[13][0] = -22, points14[13][1] = 76, points14[13][2] = 32, points14[13][3] = -32, points14[13][4] = -76, points14[13][5] = 22, points14[13][6] = 420;
	points14[14][0] = -22, points14[14][1] = 76, points14[14][2] = 32, points14[14][3] = -32, points14[14][4] = -76, points14[14][5] = 22, points14[14][6] = 440;
	points14[15][0] = -23, points14[15][1] = 80, points14[15][2] = 34, points14[15][3] = -34, points14[15][4] = -80, points14[15][5] = 23, points14[15][6] = 460;
	points14[16][0] = -23, points14[16][1] = 80, points14[16][2] = 34, points14[16][3] = -34, points14[16][4] = -80, points14[16][5] = 23, points14[16][6] = 500;
	points14[17][0] = -22, points14[17][1] = 75, points14[17][2] = 31, points14[17][3] = -31, points14[17][4] = -75, points14[17][5] = 22, points14[17][6] = 520;
	points14[18][0] = -22, points14[18][1] = 75, points14[18][2] = 31, points14[18][3] = -31, points14[18][4] = -75, points14[18][5] = 22, points14[18][6] = 540;
	points14[19][0] = -22, points14[19][1] = 72, points14[19][2] = 28, points14[19][3] = -28, points14[19][4] = -72, points14[19][5] = 22, points14[19][6] = 580;
	points14[20][0] = -21, points14[20][1] = 66, points14[20][2] = 24, points14[20][3] = -24, points14[20][4] = -66, points14[20][5] = 21, points14[20][6] = 600;
	points14[21][0] = 0, points14[21][1] = 37, points14[21][2] = 37, points14[21][3] = -37, points14[21][4] = -37, points14[21][5] = 0, points14[21][6] = 620;
	points14[22][0] = 0, points14[22][1] = 37, points14[22][2] = 37, points14[22][3] = -37, points14[22][4] = -37, points14[22][5] = 0, points14[22][6] = 640;
	points14[23][0] = 0, points14[23][1] = 0, points14[23][2] = 0, points14[23][3] = 0, points14[23][4] = 0, points14[23][5] = 0, points14[23][6] = 660;
	void *pass14 = (void *)(&points14);

	stillChecking = true;
	TaskHandle run14 = taskCreate(movePair1, TASK_DEFAULT_STACK_SIZE / 2, pass14, TASK_PRIORITY_DEFAULT);
	while (taskGetState(run14) == TASK_RUNNABLE || taskGetState(run14) == TASK_SLEEPING) {
		delay(20);
	}
	waitThenDelay(260);

	int **points15 = malloc(17 * sizeof(int *));
	for (int i = 0; i < 17; i++) {
		points15[i] = malloc(7 * sizeof(int));
	}
	points15[0][0] = 16;
	points15[1][0] = 37, points15[1][1] = -37, points15[1][2] = 37, points15[1][3] = -37, points15[1][4] = 37, points15[1][5] = -37, points15[1][6] = 20;
	points15[2][0] = 48, points15[2][1] = -48, points15[2][2] = 48, points15[2][3] = -48, points15[2][4] = 48, points15[2][5] = -48, points15[2][6] = 40;
	points15[3][0] = 48, points15[3][1] = -48, points15[3][2] = 48, points15[3][3] = -48, points15[3][4] = 48, points15[3][5] = -48, points15[3][6] = 60;
	points15[4][0] = 49, points15[4][1] = -49, points15[4][2] = 49, points15[4][3] = -49, points15[4][4] = 49, points15[4][5] = -49, points15[4][6] = 80;
	points15[5][0] = 49, points15[5][1] = -49, points15[5][2] = 49, points15[5][3] = -49, points15[5][4] = 49, points15[5][5] = -49, points15[5][6] = 320;
	points15[6][0] = 48, points15[6][1] = -48, points15[6][2] = 48, points15[6][3] = -48, points15[6][4] = 48, points15[6][5] = -48, points15[6][6] = 340;
	points15[7][0] = 48, points15[7][1] = -48, points15[7][2] = 48, points15[7][3] = -48, points15[7][4] = 48, points15[7][5] = -48, points15[7][6] = 360;
	points15[8][0] = 46, points15[8][1] = -46, points15[8][2] = 46, points15[8][3] = -46, points15[8][4] = 46, points15[8][5] = -46, points15[8][6] = 380;
	points15[9][0] = 44, points15[9][1] = -44, points15[9][2] = 44, points15[9][3] = -44, points15[9][4] = 44, points15[9][5] = -44, points15[9][6] = 400;
	points15[10][0] = 44, points15[10][1] = -44, points15[10][2] = 44, points15[10][3] = -44, points15[10][4] = 44, points15[10][5] = -44, points15[10][6] = 420;
	points15[11][0] = 34, points15[11][1] = -34, points15[11][2] = 34, points15[11][3] = -34, points15[11][4] = 34, points15[11][5] = -34, points15[11][6] = 440;
	points15[12][0] = 34, points15[12][1] = -34, points15[12][2] = 34, points15[12][3] = -34, points15[12][4] = 34, points15[12][5] = -34, points15[12][6] = 460;
	points15[13][0] = 27, points15[13][1] = -27, points15[13][2] = 27, points15[13][3] = -27, points15[13][4] = 27, points15[13][5] = -27, points15[13][6] = 480;
	points15[14][0] = 26, points15[14][1] = -26, points15[14][2] = 26, points15[14][3] = -26, points15[14][4] = 26, points15[14][5] = -26, points15[14][6] = 500;
	points15[15][0] = 26, points15[15][1] = -26, points15[15][2] = 26, points15[15][3] = -26, points15[15][4] = 26, points15[15][5] = -26, points15[15][6] = 560;
	points15[16][0] = 0, points15[16][1] = 0, points15[16][2] = 0, points15[16][3] = 0, points15[16][4] = 0, points15[16][5] = 0, points15[16][6] = 580;
	void *pass15 = (void *)(&points15);

	stillChecking = true;
	TaskHandle run15 = taskCreate(movePair1, TASK_DEFAULT_STACK_SIZE / 2, pass15, TASK_PRIORITY_DEFAULT);
	while (taskGetState(run15) == TASK_RUNNABLE || taskGetState(run15) == TASK_SLEEPING) {
		delay(20);
	}
	waitThenDelay(40);

	int **points17 = malloc(22 * sizeof(int *));
	for (int i = 0; i < 22; i++) {
		points17[i] = malloc(7 * sizeof(int));
	}
	points17[0][0] = 21;
	points17[1][0] = -23, points17[1][1] = 23, points17[1][2] = -23, points17[1][3] = 23, points17[1][4] = -23, points17[1][5] = 23, points17[1][6] = 0;
	points17[2][0] = -38, points17[2][1] = 38, points17[2][2] = -38, points17[2][3] = 38, points17[2][4] = -38, points17[2][5] = 38, points17[2][6] = 21;
	points17[3][0] = -38, points17[3][1] = 38, points17[3][2] = -38, points17[3][3] = 38, points17[3][4] = -38, points17[3][5] = 38, points17[3][6] = 41;
	points17[4][0] = -58, points17[4][1] = 58, points17[4][2] = -58, points17[4][3] = 58, points17[4][4] = -58, points17[4][5] = 58, points17[4][6] = 61;
	points17[5][0] = -58, points17[5][1] = 58, points17[5][2] = -58, points17[5][3] = 58, points17[5][4] = -58, points17[5][5] = 58, points17[5][6] = 81;
	points17[6][0] = -73, points17[6][1] = 73, points17[6][2] = -73, points17[6][3] = 73, points17[6][4] = -73, points17[6][5] = 73, points17[6][6] = 101;
	points17[7][0] = -73, points17[7][1] = 73, points17[7][2] = -73, points17[7][3] = 73, points17[7][4] = -73, points17[7][5] = 73, points17[7][6] = 121;
	points17[8][0] = -91, points17[8][1] = 91, points17[8][2] = -91, points17[8][3] = 91, points17[8][4] = -91, points17[8][5] = 91, points17[8][6] = 141;
	points17[9][0] = -103, points17[9][1] = 103, points17[9][2] = -103, points17[9][3] = 103, points17[9][4] = -103, points17[9][5] = 103, points17[9][6] = 161;
	points17[10][0] = -103, points17[10][1] = 103, points17[10][2] = -103, points17[10][3] = 103, points17[10][4] = -103, points17[10][5] = 103, points17[10][6] = 181;
	points17[11][0] = -110, points17[11][1] = 110, points17[11][2] = -110, points17[11][3] = 110, points17[11][4] = -110, points17[11][5] = 110, points17[11][6] = 201;
	points17[12][0] = -110, points17[12][1] = 110, points17[12][2] = -110, points17[12][3] = 110, points17[12][4] = -110, points17[12][5] = 110, points17[12][6] = 221;
	points17[13][0] = -118, points17[13][1] = 118, points17[13][2] = -118, points17[13][3] = 118, points17[13][4] = -118, points17[13][5] = 118, points17[13][6] = 241;
	points17[14][0] = -118, points17[14][1] = 118, points17[14][2] = -118, points17[14][3] = 118, points17[14][4] = -118, points17[14][5] = 118, points17[14][6] = 261;
	points17[15][0] = -121, points17[15][1] = 121, points17[15][2] = -121, points17[15][3] = 121, points17[15][4] = -121, points17[15][5] = 121, points17[15][6] = 281;
	points17[16][0] = -121, points17[16][1] = 121, points17[16][2] = -121, points17[16][3] = 121, points17[16][4] = -121, points17[16][5] = 121, points17[16][6] = 761;
	points17[17][0] = -114, points17[17][1] = 114, points17[17][2] = -114, points17[17][3] = 114, points17[17][4] = -114, points17[17][5] = 114, points17[17][6] = 781;
	points17[18][0] = -114, points17[18][1] = 114, points17[18][2] = -114, points17[18][3] = 114, points17[18][4] = -114, points17[18][5] = 114, points17[18][6] = 801;
	points17[19][0] = -38, points17[19][1] = 38, points17[19][2] = -38, points17[19][3] = 38, points17[19][4] = -38, points17[19][5] = 38, points17[19][6] = 821;
	points17[20][0] = -38, points17[20][1] = 38, points17[20][2] = -38, points17[20][3] = 38, points17[20][4] = -38, points17[20][5] = 38, points17[20][6] = 841;
	points17[21][0] = 0, points17[21][1] = 0, points17[21][2] = 0, points17[21][3] = 0, points17[21][4] = 0, points17[21][5] = 0, points17[21][6] = 861;
	void *pass17 = (void *)(&points17);

	TaskHandle run17 = taskCreate(movePair1, TASK_DEFAULT_STACK_SIZE / 2, pass17, TASK_PRIORITY_DEFAULT);
	while (taskGetState(run17) == TASK_RUNNABLE || taskGetState(run17) == TASK_SLEEPING) {
		delay(20);
	}
	delay(200);

	int **points16 = malloc(11 * sizeof(int *));
	for (int i = 0; i < 11; i++) {
		points16[i] = malloc(6 * sizeof(int));
	}
	points16[0][0] = 10;
	points16[1][0] = -10, points16[1][1] = -10, points16[1][2] = 10, points16[1][3] = 10, points16[1][4] = 1528, points16[1][5] = 10;
	points16[2][0] = -48, points16[2][1] = -48, points16[2][2] = 48, points16[2][3] = 48, points16[2][4] = 1528, points16[2][5] = 9;
	points16[3][0] = -77, points16[3][1] = -77, points16[3][2] = 77, points16[3][3] = 77, points16[3][4] = 1530, points16[3][5] = 10;
	points16[4][0] = -77, points16[4][1] = -77, points16[4][2] = 77, points16[4][3] = 77, points16[4][4] = 1531, points16[4][5] = 10;
	points16[5][0] = -127, points16[5][1] = -127, points16[5][2] = 127, points16[5][3] = 127, points16[5][4] = 1534, points16[5][5] = 10;
	points16[6][0] = -127, points16[6][1] = -127, points16[6][2] = 127, points16[6][3] = 127, points16[6][4] = 614, points16[6][5] = 968;
	points16[7][0] = 59, points16[7][1] = 59, points16[7][2] = -59, points16[7][3] = -59, points16[7][4] = 611, points16[7][5] = 982;
	points16[8][0] = 59, points16[8][1] = 59, points16[8][2] = -59, points16[8][3] = -59, points16[8][4] = 561, points16[8][5] = 989;
	points16[9][0] = -7, points16[9][1] = -7, points16[9][2] = 7, points16[9][3] = 7, points16[9][4] = 582, points16[9][5] = 996;
	points16[10][0] = 0, points16[10][1] = 0, points16[10][2] = 0, points16[10][3] = 0, points16[10][4] = 575, points16[10][5] = 997;
	void *pass16 = (void *)(&points16);

	TaskHandle run16 = taskCreate(movePair1, TASK_DEFAULT_STACK_SIZE / 2, pass16, TASK_PRIORITY_DEFAULT);
	while (taskGetState(run16) == TASK_RUNNABLE || taskGetState(run16) == TASK_SLEEPING) {
		delay(20);
	}
	delay(200);

	int **points19 = malloc(13 * sizeof(int *));
	for (int i = 0; i < 13; i++) {
		points19[i] = malloc(6 * sizeof(int));
	}
	points19[0][0] = 12;
	points19[1][0] = -26, points19[1][1] = -26, points19[1][2] = 26, points19[1][3] = 26, points19[1][4] = 443, points19[1][5] = 1014;
	points19[2][0] = -47, points19[2][1] = -47, points19[2][2] = 47, points19[2][3] = 47, points19[2][4] = 433, points19[2][5] = 1005;
	points19[3][0] = -116, points19[3][1] = -116, points19[3][2] = 116, points19[3][3] = 116, points19[3][4] = 425, points19[3][5] = 1018;
	points19[4][0] = -116, points19[4][1] = -116, points19[4][2] = 116, points19[4][3] = 116, points19[4][4] = 256, points19[4][5] = 1024;
	points19[5][0] = -125, points19[5][1] = -125, points19[5][2] = 125, points19[5][3] = 125, points19[5][4] = 257, points19[5][5] = 1030;
	points19[6][0] = -125, points19[6][1] = -125, points19[6][2] = 125, points19[6][3] = 125, points19[6][4] = 76, points19[6][5] = 1348;
	points19[7][0] = -122, points19[7][1] = -122, points19[7][2] = 122, points19[7][3] = 122, points19[7][4] = 56, points19[7][5] = 1358;
	points19[8][0] = -122, points19[8][1] = -122, points19[8][2] = 122, points19[8][3] = 122, points19[8][4] = 48, points19[8][5] = 1364;
	points19[9][0] = -93, points19[9][1] = -93, points19[9][2] = 93, points19[9][3] = 93, points19[9][4] = 47, points19[9][5] = 1369;
	points19[10][0] = -49, points19[10][1] = -49, points19[10][2] = 49, points19[10][3] = 49, points19[10][4] = 52, points19[10][5] = 1376;
	points19[11][0] = -49, points19[11][1] = -49, points19[11][2] = 49, points19[11][3] = 49, points19[11][4] = 47, points19[11][5] = 1381;
	points19[12][0] = 0, points19[12][1] = 0, points19[12][2] = 0, points19[12][3] = 0, points19[12][4] = 48, points19[12][5] = 1382;
	void *pass19 = (void *)(&points19);

	TaskHandle run19 = taskCreate(movePair2, TASK_DEFAULT_STACK_SIZE / 2, pass19, TASK_PRIORITY_DEFAULT);
	while (taskGetState(run19) == TASK_RUNNABLE || taskGetState(run19) == TASK_SLEEPING) {
		delay(20);
	}
	delay(200);


	int **points18 = malloc(11 * sizeof(int *));
	for (int i = 0; i < 11; i++) {
		points18[i] = malloc(7 * sizeof(int));
	}
	points18[0][0] = 10;
	points18[1][0] = 41, points18[1][1] = -41, points18[1][2] = -41, points18[1][3] = -41, points18[1][4] = -41, points18[1][5] = 41, points18[1][6] = 22;
	points18[2][0] = 61, points18[2][1] = -61, points18[2][2] = -61, points18[2][3] = -61, points18[2][4] = -61, points18[2][5] = 61, points18[2][6] = 42;
	points18[3][0] = 74, points18[3][1] = -74, points18[3][2] = -74, points18[3][3] = -74, points18[3][4] = -74, points18[3][5] = 74, points18[3][6] = 62;
	points18[4][0] = 74, points18[4][1] = -74, points18[4][2] = -74, points18[4][3] = -74, points18[4][4] = -74, points18[4][5] = 74, points18[4][6] = 82;
	points18[5][0] = 75, points18[5][1] = -75, points18[5][2] = -75, points18[5][3] = -75, points18[5][4] = -75, points18[5][5] = 75, points18[5][6] = 102;
	points18[6][0] = 75, points18[6][1] = -75, points18[6][2] = -75, points18[6][3] = -75, points18[6][4] = -75, points18[6][5] = 75, points18[6][6] = 122;
	points18[7][0] = 65, points18[7][1] = -65, points18[7][2] = -65, points18[7][3] = -65, points18[7][4] = -65, points18[7][5] = 65, points18[7][6] = 144;
	points18[8][0] = 65, points18[8][1] = -65, points18[8][2] = -65, points18[8][3] = -65, points18[8][4] = -65, points18[8][5] = 65, points18[8][6] = 164;
	points18[9][0] = 49, points18[9][1] = -49, points18[9][2] = -49, points18[9][3] = -49, points18[9][4] = -49, points18[9][5] = 49, points18[9][6] = 184;
	points18[10][0] = 0, points18[10][1] = 0, points18[10][2] = 0, points18[10][3] = 0, points18[10][4] = 0, points18[10][5] = 0, points18[10][6] = 204;
	void *pass18 = (void *)(&points18);

	TaskHandle run18 = taskCreate(movePair1, TASK_DEFAULT_STACK_SIZE / 2, pass18, TASK_PRIORITY_DEFAULT);
	while (taskGetState(run18) == TASK_RUNNABLE || taskGetState(run18) == TASK_SLEEPING) {
		delay(20);
	}
	delay(200);

	/*stillChecking = true;
	TaskHandle run16 = taskCreate(movePair2, TASK_DEFAULT_STACK_SIZE / 2, pass16, TASK_PRIORITY_DEFAULT);
	while ((taskGetState(run16) == TASK_RUNNING || taskGetState(run16) == TASK_RUNNABLE ||
			taskGetState(run16) == TASK_SLEEPING) && stillChecking) {
		if (nextPoint[1] >= 1 && abs(analogRead(1)) < abs(897) && abs(analogRead(2)) > abs(457)) {
			TaskHandle run17 = taskCreate(movePair1, TASK_DEFAULT_STACK_SIZE / 2, pass17, TASK_PRIORITY_DEFAULT);
		}

		delay(5);
	}
	waitThenDelay(1140);*/

	int **points21 = malloc(19 * sizeof(int *));
	for (int i = 0; i < 19; i++) {
		points21[i] = malloc(6 * sizeof(int));
	}
	points21[0][0] = 18;
	points21[1][0] = -7, points21[1][1] = -7, points21[1][2] = 7, points21[1][3] = 7, points21[1][4] = 10, points21[1][5] = 1455;
	points21[2][0] = -17, points21[2][1] = -17, points21[2][2] = 17, points21[2][3] = 17, points21[2][4] = 9, points21[2][5] = 1454;
	points21[3][0] = -26, points21[3][1] = -26, points21[3][2] = 26, points21[3][3] = 26, points21[3][4] = 9, points21[3][5] = 1455;
	points21[4][0] = -26, points21[4][1] = -26, points21[4][2] = 26, points21[4][3] = 26, points21[4][4] = 12, points21[4][5] = 1458;
	points21[5][0] = -19, points21[5][1] = -19, points21[5][2] = 19, points21[5][3] = 19, points21[5][4] = 84, points21[5][5] = 1460;
	points21[6][0] = -19, points21[6][1] = -19, points21[6][2] = 19, points21[6][3] = 19, points21[6][4] = 22, points21[6][5] = 1463;
	points21[7][0] = -16, points21[7][1] = -16, points21[7][2] = 16, points21[7][3] = 16, points21[7][4] = 12, points21[7][5] = 1464;
	points21[8][0] = -16, points21[8][1] = -16, points21[8][2] = 16, points21[8][3] = 16, points21[8][4] = 9, points21[8][5] = 1468;
	points21[9][0] = -15, points21[9][1] = -15, points21[9][2] = 15, points21[9][3] = 15, points21[9][4] = 8, points21[9][5] = 1471;
	points21[10][0] = -15, points21[10][1] = -15, points21[10][2] = 15, points21[10][3] = 15, points21[10][4] = 7, points21[10][5] = 1474;
	points21[11][0] = -16, points21[11][1] = -16, points21[11][2] = 16, points21[11][3] = 16, points21[11][4] = 10, points21[11][5] = 1477;
	points21[12][0] = -16, points21[12][1] = -16, points21[12][2] = 16, points21[12][3] = 16, points21[12][4] = 8, points21[12][5] = 1478;
	points21[13][0] = -23, points21[13][1] = -23, points21[13][2] = 23, points21[13][3] = 23, points21[13][4] = 8, points21[13][5] = 1479;
	points21[14][0] = -38, points21[14][1] = -38, points21[14][2] = 38, points21[14][3] = 38, points21[14][4] = 8, points21[14][5] = 1481;
	points21[15][0] = -38, points21[15][1] = -38, points21[15][2] = 38, points21[15][3] = 38, points21[15][4] = 8, points21[15][5] = 1482;
	points21[16][0] = -45, points21[16][1] = -45, points21[16][2] = 45, points21[16][3] = 45, points21[16][4] = 8, points21[16][5] = 1486;
	points21[17][0] = -45, points21[17][1] = -45, points21[17][2] = 45, points21[17][3] = 45, points21[17][4] = 9, points21[17][5] = 1499;
	points21[18][0] = 0, points21[18][1] = 0, points21[18][2] = 0, points21[18][3] = 0, points21[18][4] = 8, points21[18][5] = 1502;
	void *pass21 = (void *)(&points21);

	stillChecking = true;
	TaskHandle run21 = taskCreate(movePair2, TASK_DEFAULT_STACK_SIZE / 2, pass21, TASK_PRIORITY_DEFAULT);
	while (taskGetState(run21) == TASK_RUNNABLE || taskGetState(run21) == TASK_SLEEPING) {
		delay(20);
	}
	waitThenDelay(500);

	int **points20 = malloc(13 * sizeof(int *));
	for (int i = 0; i < 13; i++) {
		points20[i] = malloc(7 * sizeof(int));
	}
	points20[0][0] = 12;
	points20[1][0] = 35, points20[1][1] = -35, points20[1][2] = -35, points20[1][3] = -35, points20[1][4] = -35, points20[1][5] = 35, points20[1][6] = 21;
	points20[2][0] = 73, points20[2][1] = -73, points20[2][2] = -27, points20[2][3] = -73, points20[2][4] = -27, points20[2][5] = 27, points20[2][6] = 41;
	points20[3][0] = 73, points20[3][1] = -73, points20[3][2] = -27, points20[3][3] = -73, points20[3][4] = -27, points20[3][5] = 27, points20[3][6] = 61;
	points20[4][0] = 87, points20[4][1] = -87, points20[4][2] = -31, points20[4][3] = -87, points20[4][4] = -31, points20[4][5] = 31, points20[4][6] = 81;
	points20[5][0] = 97, points20[5][1] = -97, points20[5][2] = -35, points20[5][3] = -97, points20[5][4] = -35, points20[5][5] = 35, points20[5][6] = 101;
	points20[6][0] = 97, points20[6][1] = -97, points20[6][2] = -35, points20[6][3] = -97, points20[6][4] = -35, points20[6][5] = 35, points20[6][6] = 121;
	points20[7][0] = 101, points20[7][1] = -101, points20[7][2] = -37, points20[7][3] = -101, points20[7][4] = -37, points20[7][5] = 37, points20[7][6] = 141;
	points20[8][0] = 101, points20[8][1] = -101, points20[8][2] = -37, points20[8][3] = -101, points20[8][4] = -37, points20[8][5] = 37, points20[8][6] = 161;
	points20[9][0] = 100, points20[9][1] = -100, points20[9][2] = -36, points20[9][3] = -100, points20[9][4] = -36, points20[9][5] = 36, points20[9][6] = 181;
	points20[10][0] = 100, points20[10][1] = -100, points20[10][2] = -36, points20[10][3] = -100, points20[10][4] = -36, points20[10][5] = 36, points20[10][6] = 201;
	points20[11][0] = 75, points20[11][1] = -75, points20[11][2] = -21, points20[11][3] = -75, points20[11][4] = -21, points20[11][5] = 21, points20[11][6] = 222;
	points20[12][0] = 0, points20[12][1] = 0, points20[12][2] = 0, points20[12][3] = 0, points20[12][4] = 0, points20[12][5] = 0, points20[12][6] = 242;
	void *pass20 = (void *)(&points20);

	TaskHandle run20 = taskCreate(movePair1, TASK_DEFAULT_STACK_SIZE / 2, pass20, TASK_PRIORITY_DEFAULT);
	while (taskGetState(run20) == TASK_RUNNABLE || taskGetState(run20) == TASK_SLEEPING) {
		delay(20);
	}
	delay(200);

	free(nextPoint);
}
