#pragma config(StandardModel, "VEX Launchbot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Nothing But Net - Launchbot - Autonomous Scoring (Natural Language)
-This program will move across the field and will launch the balls into the high goal,

Robot Model: VEX Launchbot
Starting Point: RED | LEFT
----------------------------------------------------------------------------------------------------*/

void launchBalls(float speed)  //This function will launch the loaded balls at the speed defined below
{
	resetMotorEncoder(loadMotor);

	setMultipleMotors(speed, rightIntakeMotor, leftIntakeMotor);//Set the intake motors to the power defined
	setMotor(loadMotor, -speed);//Set the load motor to the opposite power.
	waitUntil(getMotorEncoder(loadMotor) <= -1000);//While the load motor is less than -1000 counts...
	stopAllMotors(); //Stop the motors after launch completes
}

void intakeBalls(float speed)
{
	resetMotorEncoder(loadMotor);

	setMultipleMotors(-speed, rightIntakeMotor,leftIntakeMotor);
	setMotor(loadMotor,speed);
  setMultipleMotors(speed-15,frontLeftMotor,frontRightMotor,leftMotor,rightMotor);
	waitUntil(getMotorEncoder(loadMotor) <= -35);
	stopAllMotors();

}



task main()
{


  forward(.76,rotations,127);

	turnLeft(292,degrees,127);

	forward(4,rotations,127);

	moveMotor(armMotor,165,degrees,-127);

	launchBalls(127);

	backward(3,rotations,127);

	moveMotor(armMotor,165,degrees,127);

	turnRight(80,degrees,127);

	resetMotorEncoder(frontLeftMotor);

	forward(.5,rotations,127);

	intakeBalls(127);




	wait1Msec(1000);

}
